# pylint: skip-file
# Generated by Django 5.2.13 on 2026-04-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('identifier', models.SlugField(max_length=1024)),
                ('source', models.URLField(blank=True, max_length=1024, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='sft_ip_address_databases')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IP address database',
                'verbose_name_plural': 'IP address databases',
            },
        ),
    ]
